image: index.docker.io/ericwf/libcxx-gitlab-runner:latest
variables:
  ROOT_DIR: $CI_BUILDS_DIR/$CI_PROJECT_NAMESPACE
  LIBCXX_DIR: $CI_PROJECT_DIR
  LLVM_DIR: $ROOT_DIR/llvm
  LIBCXXABI_DIR: $ROOT_DIR/libcxxabi
  LIBCXX_SOURCE_ROOT: $CI_BUILDS_DIR/libcxx-root/libcxx


stages:
  - prepare
  - build
  - test
  - finish

prepare:
  stage: prepare
  script:
    - ls
    - pwd
    - ls ..
    - env
    - cd $LIBCXX_DIR
    - mkdir /tmp/libcxx-tmp
    - mv -t /tmp/libcxx-tmp *
    - mv /tmp/libcxx-tmp/ libcxx/
    - mkdir build/
    - touch build/artifact
  artifacts:
    when: always
    paths:
      - libcxx/
      - build/

build:
  stage: build
  script:
    - ls
    - ls build/

  dependencies:
    - prepare

test:
  stage: test
  script:
    - echo "test"
  dependencies:
    - build

finish:
  stage: finish
  script:
    - echo "finish"
  dependencies:
    - prepare
    - build
    - test
