image: index.docker.io/ericwf/libcxx-gitlab-runner:latest
variables:
  ROOT_DIR: $CI_BUILDS_DIR/$CI_PROJECT_NAMESPACE
  LIBCXX_DIR: $CI_PROJECT_DIR
  LLVM_DIR: $ROOT_DIR/llvm
  LIBCXXABI_DIR: $ROOT_DIR/libcxxabi
  LIBCXX_SOURCE_ROOT: $CI_BUILDS_DIR/libcxx-root/libcxx

stages:
  - prepare
  - build
  - test
  - finish

prepare:
  stage: prepare
  script:
    - ls
    - pwd
    - ls ..
    - cd ..
    - pwd
    - env

build:
  stage: build
  script:
    - ls
    - pwd
    - ls ..
    - pwd
    - env
    - echo "build"
    - ls
    - clang++ --version
    - ninja --version
    - cmake --version
  dependencies:
    - prepare

test:
  stage: test
  script:
    - echo "test"
  dependencies:
    - build

finish:
  stage: finish
  script:
    - echo "finish"
  dependencies:
    - prepare
    - build
    - test
