image: index.docker.io/ericwf/libcxx-gitlab-runner:latest
variables:
  ROOT: $CI_PROJECT_DIR/
  GIT_STRATEGY: none

stages:
  - env
  - stage_all
  - stage_projects
  - configure
  - build
  - test
  - finish

cache:
  untracked: true
  paths:
    - llvm-project/
    - ci/$CI_PROJECT_PATH/
    - stage/STAGE_HERE
    - build/BUILD_HERE

env:
  stage: env
  script:
    - env
    - pwd
    - ls
    - ls ..
    - ls ../..
    - clang++ --version
    - g++ --version
    - cmake --version
    - ninja --version


stage_all:
  stage: stage_all
  variables:
    GIT_STRATEGY: clone
  script:
    - env
    - pwd
    - mkdir -p /tmp/$CI_PROJECT_PATH
    - mv -t /tmp/$CI_PROJECT_PATH/ *
    - ls
    - mkdir build/ stage/ ci/
    - mv /tmp/$CI_PROJECT_NAMESPACE ci/
    - git clone --depth=1 https://github.com/llvm/llvm-project.git llvm-project/
    - touch build/BUILD_HERE
    - touch stage/STAGE_HERE
    - ls

stage_projects:libcxx:
  stage: stage_projects
  script:
    - pwd
    - ls
    - mkdir stage/libcxx
    - cp -R llvm-project/ stage/libcxx/llvm-project
    - rm -rf stage/libcxx/llvm-project/libcxx
    - cp -R ci/$CI_PROJECT_NAMESPACE/libcxx stage/libcxx/llvm-project/libcxx
    - mkdir build/libcxx
  artifacts:
    when: always
    paths:
      - stage/libcxx/llvm-project/
      - build/libcxx/

configure:libcxx:
  stage: configure
  variables:
    LLVM_PROJECT: stage/libcxx/llvm-project
    SOURCE: stage/libcxx/llvm-project/libcxx
    BUILD: build/libcxx
  script:
    - echo "configure"
    - mkdir $BUILD
    - cd $BUILD
    - cmake -G Ninja -DCMAKE_BUILD_TYPE=RELWITHDEBINFO -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ "-DLLVM_ENABLE_PROJECTS=libcxx;libcxxabi" $LLVM_PROJECT/llvm
  artifacts:
    when: always
    paths:
      - build/libcxx/
  dependencies:
    - stage_projects:libcxx

build:libcxx:
  stage: build
  script:
    - ls
    - cd build/libcxx
    - ninja cxx
  dependencies:
    - configure:libcxx
  artifacts:
    when: always
    paths:
      - build/libcxx/

test:libcxx:
  stage: test
  script:
      - ls
      - cd build/libcxx
      - ninja checx-cxx
  dependencies:
    - build:libcxx

finish:
  stage: finish
  script:
    - echo "finish"
