image: index.docker.io/ericwf/libcxx-buildbot-base:latest
variables:
  GIT_CLONE_PATH: $CI_BUILDS_DIR/libcxx-root/libcxx
  JOB_ROOT: $CI_BUILDS_DIR/libcxx-root
  LIBCXX_SOURCE_ROOT: $CI_BUILDS_DIR/libcxx-root/libcxx

stages:
  - prepare
  - build
  - test
  - finish

prepare:
  stage: prepare
  script:
    - git clone --depth=1 https://git.llvm.org/llvm.git $JOB_ROOT/llvm
    - git clone --depth=1 https://git.llvm.org/libcxxabi.git $JOB_ROOT/llvm/projects/libcxxabi
    - cp -R $LIBCXX_SOURCE_ROOT $JOB_ROOT/llvm/projects/libcxx
    - cd $JOB_ROOT
    - ls
    - pwd
    - ls ..
    - cd ..
    - pwd
    - env

build:
  stage: build
  script:
    - echo "build"
    - ls
    - clang++ --version
    - ninja --version
    - cmake --version
  dependencies:
    - prepare

test:
  stage: test
  script:
    - echo "test"
  dependencies:
    - build

finish:
  stage: finish
  script:
    - echo "finish"
  dependencies:
    - prepare
    - build
    - test
