image: index.docker.io/ericwf/libcxx-gitlab-runner:latest
variables:
  ROOT_DIR: $CI_BUILDS_DIR/$CI_PROJECT_NAMESPACE
  LIBCXX_DIR: $CI_PROJECT_DIR
  LLVM_DIR: $ROOT_DIR/llvm
  LIBCXXABI_DIR: $ROOT_DIR/libcxxabi
  LIBCXX_SOURCE_ROOT: $CI_BUILDS_DIR/libcxx-root/libcxx


stages:
  - prepare
  - build
  - test
  - finish

prepare:
  stage: prepare
  script:
    - ls
    - pwd
    - ls ..
    - env
    - cp -R $CI_PROJECT_DIR/ /tmp/libcxx.orig
    - mkdir ci/
    - git clone --depth=1 https://github.com/llvm/llvm-project.git ci/llvm-project
    - rm -rf ci/llvm-project/libcxx/
    - cp -R  /tmp/libcxx.orig /tmp/llvm-project/libcxx
    - mkdir ci/build
    - touch ci/build/hello
  artifacts:
    when: always
    paths:
      - ci/llvm-project/
      - ci/build/

build:
  stage: build
  script:
    - ls
    - ls ci/
  dependencies:
    - prepare

test:
  stage: test
  script:
    - echo "test"
  dependencies:
    - build

finish:
  stage: finish
  script:
    - echo "finish"
  dependencies:
    - prepare
    - build
    - test
