image: index.docker.io/ericwf/libcxx-buildbot-base:latest

stages:
  - prepare
  - build
  - test
  - finish

prepare:
  stage: prepare
  script:
    - echo "prepare"
    - ls
    - pwd
    - ls ..
    - cd ..
    - pwd
    - env

build:
  stage: build
  script:
    - echo "build"
    - ls
    - clang++ --version
    - ninja --version
    - cmake --version
  dependencies:
    - prepare

test:
  stage: test
  script:
    - echo "test"
  dependencies:
    - build

finish:
  stage: finish
  script:
    - echo "finish"
  dependencies:
    - prepare
    - build
    - test
