image: index.docker.io/ericwf/libcxx-gitlab-runner:latest
variables:
  ROOT: $CI_PROJECT_DIR/
  GIT_STRATEGY: none

stages:
  - stage_all
  - stage_projects
  - build
  - test

.staged-env:
  artifacts:
    when: always
    paths:
      - llvm-project/
      - ci/$CI_PROJECT_PATH/
      - stage/
      - build/

.staged-libcxx:
  extends: .staged-env
  variables:
    PROJECT_NAME: "libcxx"
    LLVM_PROJECT: "$CI_PROJECT_DIR/stage/libcxx/llvm-project"
    SOURCE: "$CI_PROJECT_DIR/stage/libcxx/llvm-project/libcxx"
    BUILD: "$CI_PROJECT_DIR/build/libcxx"
  artifacts:
    when: always
    paths:
      - stage/libcxx/llvm-project/
      - build/libcxx/

stage_all:libcxx:
  extends: .staged-env
  stage: stage_all
  variables:
    GIT_STRATEGY: clone
  script:
    - ./utils/gitlab/display_environment.sh
    - cp ./utils/gitlab/stage_llvm_sources.sh /tmp/
    - /tmp/stage_llvm_sources.sh
    - echo "Done staging sources"

stage_projects:libcxx:
  extends: .staged-libcxx
  stage: stage_projects
  script:
    - pwd
    - ls
    - mkdir stage/libcxx
    - cp -R llvm-project/ stage/libcxx/llvm-project
    - rm -rf stage/libcxx/llvm-project/libcxx
    - cp -R ci/$CI_PROJECT_NAMESPACE/libcxx stage/libcxx/llvm-project/libcxx
    - mkdir -p build/libcxx

build:libcxx:
  extends: .staged-libcxx
  stage: build
  variables:
    CC: clang
    CXX: clang++
    BUILD_TYPE: RELWITHDEBINFO
    LLVM_LIT_ARGS: -sv --show-xfail --show-unsupported --xunit-xml-output=$BUILD_LIBCXX/test-results.xml"
  script:
    - env
    - echo "configure"
    - cd $BUILD
    - cmake -G Ninja -DCMAKE_BUILD_TYPE=$BUILD_TYPE \
       -DCMAKE_C_COMPILER=$CC \
       -DCMAKE_CXX_COMPILER=$CXX \
       "-DLLVM_ENABLE_PROJECTS=libcxx;libcxxabi" \
       "-DLLVM_LIT_ARGS=$LLVM_LIT_ARGS" \
       "$LLVM_PROJECT/llvm"
    - ninja cxx
  dependencies:
    - stage_projects:libcxx

test:libcxx:
  extends: .staged-libcxx
  stage: test
  script:
      - ls
      - cd build/libcxx
      - ninja check-cxxabi
      - ninja check-cxx
      - ninja check-cxx-benchmarks
      - ninja check-cxx-abilist
  dependencies:
    - build:libcxx
  artifacts:
    when: always
    reports:
      junit: $BUILD_LIBCXX/test-results.xml
