version: '{build}'

shallow_clone: true

build:
  verbosity: detailed

configuration:
  - Debug

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      MINGW_PATH: C:\mingw-w64\i686-6.3.0-posix-dwarf-rt_v5-rev1\mingw32\bin
      GENERATOR: MinGW Makefiles
      MAKE_PROGRAM: mingw32-make
      CMAKE_OPTIONS: -DLIBCXX_ENABLE_STATIC=OFF -DLIBCXXABI_ENABLE_SHARED=OFF -DLIBCXX_ENABLE_STATIC_ABI_LIBRARY=ON
      USE_LIBCXXABI: ON
      APPVEYOR_SAVE_CACHE_ON_ERROR: true
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CMAKE_OPTIONS: -DCMAKE_C_COMPILER=clang-cl.exe -DCMAKE_CXX_COMPILER=clang-cl.exe
      CLANG_VERSION: ToT
      MSVC_SETUP_PATH: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat
      MSVC_SETUP_ARG: x86
      GENERATOR: Ninja
      MAKE_PROGRAM: ninja
      APPVEYOR_SAVE_CACHE_ON_ERROR: true
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      CMAKE_OPTIONS: -DCMAKE_C_COMPILER=clang-cl.exe -DCMAKE_CXX_COMPILER=clang-cl.exe
      CLANG_VERSION: 4
      MSVC_SETUP_PATH: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat
      MSVC_SETUP_ARG: x86_amd64
      GENERATOR: Ninja
      MAKE_PROGRAM: ninja
      APPVEYOR_SAVE_CACHE_ON_ERROR: true


install:
  ############################################################################
  # All external dependencies are installed in C:\projects\deps
  ############################################################################
  - call "%APPVEYOR_BUILD_FOLDER%\\appveyor-reqs-install.cmd"

before_build:
  - if DEFINED MSVC_SETUP_PATH call "%MSVC_SETUP_PATH%" %MSVC_SETUP_ARG%
  - cd %APPVEYOR_BUILD_FOLDER%

build_script:
  - md C:\projects\build-libcxx
  - cd C:\projects\build-libcxx
  - echo %configuration%

  #############################################################################
  # Configuration Step
  #############################################################################
  - cmake -G "%GENERATOR%" %CMAKE_OPTIONS%
    "-DCMAKE_BUILD_TYPE=%configuration%"
    -DLLVM_FORCE_BUILD_RUNTIME=ON
    -DLIBCXX_ENABLE_EXPERIMENTAL_LIBRARY=OFF
    -DLLVM_LIT_ARGS="-sv --show-xfail --show-unsupported"
    C:\projects\llvm

  #############################################################################
  # Build Step
  #############################################################################
  - "%MAKE_PROGRAM% cxx"

test_script:
  #- "%MAKE_PROGRAM% check-cxx"
  - echo FIXME tests disabled...

on_failure:
  - appveyor PushArtifact CMakeFiles/CMakeOutput.log
  - appveyor PushArtifact CMakeFiles/CMakeError.log

artifacts:
  - path: '_build/CMakeFiles/*.log'
    name: logs

cache:
 - C:\projects\deps\ninja -> appveyor.yml
 - C:\projects\deps\cmake -> appveyor.yml
