version: '3.7'

x-build-clang: &build-clang
    context: .
    dockerfile: clang.Dockerfile

x-build-gcc: &build-gcc
    context: .
    dockerfile: gcc.Dockerfile

services:
  gcc-5:
    build:
      <<: *build-gcc
      args:
        branch: gcc-5_5_0-release
        install_prefix: /opt/gcc-5
    image: ericwf/gcc-5
  llvm-4:
    build:
      <<: *build-clang
      args:
        branch: release/4.x
        install_prefix: /opt/llvm-4
    image: ericwf/llvm-4
  gcc-tot:
    build:
      <<: *build-gcc
      args:
        branch: master
        install_prefix: /opt/gcc-tot
    image: ericwf/gcc-tot
  llvm-tot:
    build:
      <<: *build-clang
      args:
        branch: master
        install_prefix: /opt/llvm-tot
    image: ericwf/llvm-tot

