version: '3.7'


services:
  llvm-buildbot-worker:
    build:
      context: .
      dockerfile: buildbot/llvm-buildbot-worker.Dockerfile
      target: llvm-buildbot-worker
    image: ericwf/llvm-buildbot-worker:latest
