version: '3.4'
services:
  builder-base:
    build:
      context: .
      dockerfile: debian9/Dockerfile.base
      target: builder-base
    image: ericwf/builder-base:latest
  compilers:
    build:
      context: .
      dockerfile: debian9/Dockerfile.compilers
      target: compilers
    image: ericwf/compilers:latest
  compilers-tot-builder:
    build:
      context: .
      dockerfile: debian9/Dockerfile.compilers_tot
      target: compilers-tot
    image: ericwf/compilers-tot:latest
  buildbot:
    build:
      context: .
      dockerfile: debian9/Dockerfile.buildbot
      target: buildbot
    image: ericwf/libcxx-buildbot-base:latest
