version: '3.4'
services:
  llvm-gitlab-runner-service:
    build:
      context: .
      dockerfile: Dockerfile.gitlab_runner_service
      target: llvm-gitlab-runner-service
      secrets:
        - llvm_gitlab_secret
    image: ericwf/llvm-gitlab-runner-service:latest
secrets:
  llvm_gitlab_secret:
    external: true

